{
 "title": "Kafka Connect Monitoring2",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Connector Tasks Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count)"
    }
   ]
  },
  {
   "title": "Connector Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count)"
    }
   ]
  },
  {
   "title": "Connector Task Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_total_task_count)"
    }
   ]
  },
  {
   "title": "Connector Task Success",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_task_startup_success_total"
    }
   ]
  },
  {
   "title": "task offset commit success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_success_percentage",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "Task Commit Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_avg_time_ms",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "Task Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (task_id) (rate(kafka_connect_task_error_metrics_total_record_errors[5m]))",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "Task Record Poll Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (task_id) (rate(kafka_connect_source_task_metrics_source_record_poll_total[5m]))",
     "legendFormat": "{{task_id}}"
    }
   ]
  }
 ]
}