global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']

#  - job_name: 'spring-actuator'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 1s
#    static_configs:
#      - targets: [ '{your ip address}:8080' ]


  - job_name: 'kafka-connect'
    static_configs:
      - targets: [ 'exam-connect:5556' ]